### ISSUE TITLE
can we config to input force or mandatory update?

### ISSUE THREAD

**Issue by Akanksha-1011** [rwbutler/Updates#20]
Hi, 

this is just a question that if there are new version available on App Store and I want to make it mandatory update like if you are not update to new version you can not use the so basically without update he should blocked for use of the app.

**Comment by rwbutler** [comment]
Thanks @leopic that's correct - I've also tried to build the framework so that adopters aren't forced to utilise the out-of-the-box UI since a lot of developers will want to implement their own custom UI. In this case, it should be possible to read the value of the flag and do the right thing with their app UI accordingly.
